buildVariable: true
category:
- SERIF
familyName: Noto Serif Tamil
googleFonts: true
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoSerifTamil.glyphs
- NotoSerifTamil-Italic.glyphs
