buildVariable: false
familyName: Noto Sans Tamil Supplement
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoSansTamilSupplement.designspace
